### ISSUE TITLE
App  in the foreground，Message UI problem

### ISSUE THREAD

**Issue by wujunyang** [Iterable/swift-sdk#127]
Hello, I have successfully integrated Iterable-iOS-SDK, but when I tried to send push messages [Message Medium (Push)], if APP was running in the foreground（UIApplicationStateInactive）, it found that the method of calling Iterable had no UI effect, received messages but did not show the UI, does SDK support this kind of display at present?

-(void)application:(UIApplication *)application didReceiveRemoteNotification:(nonnull NSDictionary *)userInfo fetchCompletionHandler:(nonnull void (^)(UIBackgroundFetchResult))completionHandler
{
   [IterableAppIntegration application:application didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

I tried to see the effect of SDK implementation, that in the active state, they are all direct breaks.

IterableAppIntegration：

func application(_ application: ApplicationStateProviderProtocol, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: ((UIBackgroundFetchResult)->Void)?) {
…..

            switch application.applicationState {
            case .active:
                break
            case .background:
                break
…..
}

**Comment by roninopf** [comment]
Hi @wujunyang, thanks for writing in; hmm, I'm trying to understand the full context of the linked code, but would you be able to file a ticket with your support rep? They may already have the answer you're looking for, and will also know to collect specific information for us to process; the ticket will then be tracked internally so we can schedule and allocate time to it.

In the mean time, I'll look in to this!
