### ISSUE TITLE
Data to hex conversion not working as expected

### ISSUE THREAD

**Issue by ferrous777** [Iterable/swift-sdk#170]
`public extension Data {
    //from: https://stackoverflow.com/questions/39075043/how-to-convert-data-to-hex-string-in-swift
    func hexString() -> String {
        let digits = Array("01234567890abcdef".utf16)

        var chars: [UniChar] = []
        chars.reserveCapacity(count * 2)

        for byte in self {
            chars.append(digits[Int(byte / 16)])
            chars.append(digits[Int(byte % 16)])
        }

        return String(utf16CodeUnits: chars, count: chars.count)
    }
}`

This code was added but doesn't work as expected. We are printing the hex bits before sending them to the iterable SDK and the values are not the same. Our method for printing the hex bits is below and when we use that value in place of the implementation above, our device tokens in iterable work with APNS and we actually receive push notifications.

`let token = deviceToken.map { String(format: "%02.2hhx", $0) }.joined()`

**Comment by tapashmajumder** [comment]
Aha. If this is true then you may have saved us some headache.

**Comment by tapashmajumder** [comment]
@ferrous777 Can you please add an example of what is not working?

**Comment by ferrous777** [comment]
`▿ 32 bytes
  - count : 32
  ▿ pointer : 0x00000002814a6b90
    - pointerValue : 10759072656
  ▿ bytes : 32 elements
    - 0 : 247
    - 1 : 5
    - 2 : 203
    - 3 : 145
    - 4 : 235
    - 5 : 99
    - 6 : 213
    - 7 : 130
    - 8 : 232
    - 9 : 110
    - 10 : 173
    - 11 : 72
    - 12 : 43
    - 13 : 96
    - 14 : 152
    - 15 : 174
    - 16 : 43
    - 17 : 69
    - 18 : 130
    - 19 : 200
    - 20 : 42
    - 21 : 52
    - 22 : 59
    - 23 : 217
    - 24 : 96
    - 25 : 210
    - 26 : 179
    - 27 : 110
    - 28 : 212
    - 29 : 115
    - 30 : 87
    - 31 : 196`

For the above data object, the conversion using the hexString method is:

e705ba91da63c582d86d0c482a60980d2a4582b820343ac960c2a36dc47357b4

Using our map function to convert to hex:

f705cb91eb63d582e86ead482b6098ae2b4582c82a343bd960d2b36ed47357c4

When we use the first hex value, we don't get pushes. When we make the registration call with the second hex value, we get pushes.

**Comment by tapashmajumder** [comment]
Thank you. Thank you. Thank you.

**Comment by tapashmajumder** [comment]
Be ready for an immediate patch. Which SDK version are you using?

**Comment by ferrous777** [comment]
we just updated to 6.1.1

**Comment by tapashmajumder** [comment]
Please update to version 6.1.2. That has your fix.
