### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by ambujpunn** [Iterable/swift-sdk#174]
Unable to import the IterableSDK framework on Xcode 11.

Seems like the framework needs to be rebuilt using the latest Xcode 11 (now that it has been released) on the App Store.

**Comment by tapashmajumder** [comment]
Which version of the SDK are you trying to use? Also are you using Cocoapods or using the SDK files directly.
Please add error message and more details here.

**Comment by ambujpunn** [comment]
I tried with the latest version `6.1.2`, and installing manually (without pods or carthage). The error message I receive is:
`Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler` when importing the IterableSDK

**Comment by tapashmajumder** [comment]
Got it. Thanks! We will release a new version shortly with XCode 11. It would probably early next week.

**Comment by ambujpunn** [comment]
@tapashmajumder thanks! will wait for that 👍

**Comment by tapashmajumder** [comment]
We have updated the zip files in the release with new binaries Swift 5.1.
