### ISSUE TITLE
Ordering of in-app messages

### ISSUE THREAD

**Issue by vrutberg** [Iterable/swift-sdk#203]
Hi,

I have a question regarding ordering of in-app messages sent to a user. The docs mention that in-app messages are stored in a queue, which would imply a first in, first out (FIFO) behavior. 

Let's say I send three in-app messages to user A, in the following order: `M1`, `M2`, `M3`.

If I then do this: `IterableAPI.inAppManager.getMessages().first`, which message would that be? The one that the user received first (M1), or the last one sent (M3)?

Thanks
Viktor

**Comment by tapashmajumder** [comment]
Hi @vrutberg  The messages should arrive in the order they were sent. So in your case it should be M1. Having said that I remember there being a discussion about it and I believe we fixed the issue. Are you noticing anything different? 

If you are seeing a bug, please let us know the version of SDK that you are testing on.

**Comment by vrutberg** [comment]
Thanks for clarifying @tapashmajumder, that is also what I was expecting. We're seeing different behaviors on our iOS and Android apps -- but it could be because of different implementations in our apps. In the iOS app we manually display the in-app messages using `IterableAPI.inAppManager.getMessages()`, whereas in the Android app we let the SDK handle it for us.

I think we'll manage to sort it out. Thanks again!
