### ISSUE TITLE
Use of NoneLogDelegate

### ISSUE THREAD

**Issue by keithbertelsen** [Iterable/swift-sdk#214]
I am trying to understand how I can use `NoneLogDelegate`, so that I can turn Iterable logging off as appropraite. When in my AppDelegate I write

```
let iterableConfig = IterableConfig()
iterableConfig.logDelegate = NoneLogDelegate()
```

I get the error

```
'NoneLogDelegate' initializer is inaccessible due to 'internal' protection level
```

Is there a different way of initializing an `IterableConfig` object with a `NoneLogDelegate` to avoid this issue?

**Comment by tapashmajumder** [comment]
`public class MyCustomDelegate: IterableLogDelegate {
    public func log(level _: LogLevel = .info, message _: String) {
        // Do nothing
    }
}
// now set this 
iterableConfig.logDelegate = MyCustomDelegate()
`

**Comment by tapashmajumder** [comment]
```
// create your own log delegate
public class MyCustomLogDelegate: IterableLogDelegate {
    public func log(level _: LogLevel = .info, message _: String) {
        // Do nothing
    }
}
// now set this 
config.logDelegate = MyCustomLogDelegate()
```

**Comment by keithbertelsen** [comment]
If that allows me to log nothing, and `NoneLogDelegate` cannot actually be used, why does `NoneLogDelegate` exist, and in particular, why does the documentation for `logDelegate` imply that you can select it (by indicating that it's "out of the box"?

**Comment by tapashmajumder** [comment]
Yes having this is confusing. We will fix this in future version. For now please proceed with the solution above.

**Comment by keithbertelsen** [comment]
Okay, thanks :)

**Comment by roninopf** [comment]
This is fixed with the above PR, and it'll be included in the next SDK release! Thanks for bringing it to our attention. If there's an issue arising from this, feel free to open a new ticket.
