### ISSUE TITLE
Not getting actual universal link 

### ISSUE THREAD

**Issue by rashidbinlatheef** [Iterable/swift-sdk#260]
Consider universal link www.example.com/samplePath.
When we create an email template with  this link, Iterable check for AASA details and creates 
mapping links2.example.com/12345 -> www.example.com/samplePath.

On clicking the rewritten link from email, app should be opened and we should get a call back in iterableURLDelegate method with original Url ie www.example.com/samplePath.  As of now getting the mapped URL only, not the original one.

**Comment by rashidbinlatheef** [comment]
checked the code and URLSessionDelegate implementation in IterableDeeplinkManager, not executing redirect link

**Comment by tapashmajumder** [comment]
@rashidbinlatheef We need more information to debug this issue.

Here the comment from our engineer to you in our Slack channel. "What is the rewritten link URL? Could you send it to me through direct messages (not in this thread)?"

**Comment by roninopf** [comment]
Ah, we've resolved this as being related to allowing arbitrary loads (HTTP links) in your app, sorry for the confusion!
