### ISSUE TITLE
please remove `public` from `extension UIColor`

### ISSUE THREAD

**Issue by RolandasRazma** [Iterable/swift-sdk#269]
please remove `public` from `extension UIColor` as you conflicting with other implementations out there

https://github.com/Iterable/swift-sdk/blob/fbd7145400309a1a3ffcfa5400906c148b9ad15b/swift-sdk/Internal/ClassExtensions.swift#L75

**Comment by roninopf** [comment]
Hi @RolandasRazma ! Thanks for writing in. We just released 6.2.1 to fix this. If there's any further issues, please feel free to open a new issue.
