### ISSUE TITLE
Multiple commands produce Assets.car

### ISSUE THREAD

**Issue by ileitch** [Iterable/swift-sdk#270]
6.2.0 uses `resource` in the podspec, which means this version cannot be used in projects that use static libraries due to a name conflict.

The cocoapods documentation strongly recommends using [resource_bunldes](https://guides.cocoapods.org/syntax/podspec.html#resource_bundles) instead to avoid this.

**Comment by tapashmajumder** [comment]
@ileitch  Can you please try using Swift Package Manager to import IterableSDK to your project? That should solve the problem with static libraries.

File -> Swift Packages -> https://github.com/Iterable/swift-sdk.git

**Comment by ileitch** [comment]
I’m afraid that’s not possible, our project is completely dependent on CocoaPods currently.

**Comment by tapashmajumder** [comment]
Unless I am missing something, you can still continue to use cocoapods for other dependencies. 

Just for IterableSDK you can try Swift package manager. It should probably take less than a minute to check it.

**Comment by ileitch** [comment]
Sorry, I wasn't clear in my last message. The point I was trying to make is that simply introducing SPM into our workflow isn't a 1 minute thing. We've multiple teams using this project, a pretty complex CI setup and an automated release process. Supporting two package managers isn't really a viable solution for us at this time.

Is there a reason that Iterable can't use a resource bundle like other pods?

**Comment by tapashmajumder** [comment]
Thanks! I understand what you are saying now. It will take us some time to validate the solution that you are suggesting. We need to make sure that this change won't break other users who are not using our Pod as a static library.

**Comment by owattenmaker** [comment]
The workaround I found was in Xcode `File->Workspace Settings` and changing build system to `Legacy Build System`. Ideally this would be fixed as described above, but if you need to push a feature out the door then it will at least get the build passing.

**Comment by roninopf** [comment]
Hi @ileitch , thanks for writing in. We've put a fix for this in `6.2.2`. Please feel free to open a new issue if one arises.
