### ISSUE TITLE
LogLevel name conflict with other SDK

### ISSUE THREAD

**Issue by osawhoop** [Iterable/swift-sdk#272]
Hello,

It could be possible to change the name of the class LogLevel since we have a conflict with another class in other SDK, we noticed that Google Analytics has defined their log level class as GAILogLevel so I wonder if you could do something similar, since we added Iterable SDK we have this conflict with another SDK from Nordic Semiconductor which we have been using since last year, we just added Iterable SDK to our project so it would be great if you could add that change, we will appreciate.

**Comment by tapashmajumder** [comment]
Hi @osawhoop,

 Can you please try to disambiguate `LogLevel` by setting it as `IterableSDK.Loglevel` or `OtherSDK.LogLevel`?

Also can you please post the error message here?

**Comment by osawhoop** [comment]
Hi Tapash,
I don't think I can do that since both SDK defined the class LogLevel with the same name so I would need to change the definition of the class in the source code and every time I update the pod I will need to do that. So I wonder if you could do something that Google did with their log class declared as GAILogLevel so maybe you can defined as ITBLLogLevel, we will really appreciate.
This is the error:
`In file included from /.../Code/AppDelegate/WHPAppDelegate.mm:40:
/.../Build/Products/Debug-iphoneos/Iterable-iOS-SDK/IterableSDK.framework/Headers/IterableSDK-Swift.h:1194:31: error: redefinition of 'LogLevel'
typedef SWIFT_ENUM(NSInteger, LogLevel, closed) {
                              ^
In file included from /.../Code/AppDelegate/WHPAppDelegate.mm:33:
In file included from ...-Bridging-Header.h:108:
/.../Build/Products/Debug-iphoneos/iOSDFULibrary/iOSDFULibrary.framework/Headers/iOSDFULibrary-Swift.h:929:31: note: previous definition is here
typedef SWIFT_ENUM(NSInteger, LogLevel, closed) {
                              ^
1 error generated.`

**Comment by tapashmajumder** [comment]
Hi @osawhoop thanks for your response. I see that you are using an Objective C project so there is no concept of namespace there. We will look into it.

**Comment by roninopf** [comment]
Hi @osawhoop, we've put a fix for this in `6.2.2`; it's been given an Objective-C specific name (`IterableLogLevel`) so it shouldn't be colliding anymore. Please feel free to open a new issue if one arises. Thanks!
