### ISSUE TITLE
IterableHtmlMessageViewController with no content and blocking interaction with the app

### ISSUE THREAD

**Issue by osawhoop** [Iterable/swift-sdk#275]
Hello Iterable Team,
I noticed a bug in the app that when a button has no "action" or "url" is empty the SDK add a IterableHtmlMessageViewController on top of the hierarchy blocking any interaction with the app, the user needs to force quit the app in order to continue using it, I wonder if could you add some validation in the SDK to prevent this behavior.

this is an example of the template I'm using:
`<a class="btn" href="">LET ME SEE !</a> <a class="btn2" href="action://dismiss">I'M GOOD</a>`
the button "I'M GOOD" close the in-app message but the button "LET ME SEE!" trigger to show the IterableHtmlMessageViewController with no content blocking the interaction with the app. I'm using the SDK 6.2.0

Thanks! and keep doing a great job with this SDK! we love it!

<img width="379" alt="Screen Shot 2020-03-03 at 9 09 08 AM" src="https://user-images.githubusercontent.com/43786155/75784152-c77e2300-5d2f-11ea-8871-d80e5677e5af.png">

**Comment by tapashmajumder** [comment]
Sorry our SDK does not support buttons with blank hrefs.

Our UI does not even allow you to save an in-app without at least one valid href link. So, in this case, if you remove the "I'M GOOD" button, you won't be able to save this in-app.

**Comment by osawhoop** [comment]
oh I did not know about that, thank you!
