### ISSUE TITLE
How to resolve URL

### ISSUE THREAD

**Issue by kwakueshun** [Iterable/swift-sdk#295]
Previously our app was able to use 
`ITEActionBlock` to get a resolved value of the useractivity's URL and pass it to `getAndTrackDeeplink` for a custom action. This is now deprecated and would break our setup. Is there a way to just retrieve the resolved value when we receive the url inside of app delegate's
`- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler`? 

Thanks.

**Comment by tapashmajumder** [comment]
1. In `application:continueUserActivity:...` method add 
`IterableAPI.handle(universalLink: "https://xyz")

2. In AppDelegate
set IterableConfig.urlDelegate = self

3. Now you will get a callback with the resolved url

```
func handle(iterableURL url: URL, inContext context: IterableActionContext) -> Bool {
    // You will get resolved url here
}
````

Please see here for more information
https://github.com/iterable/swift-sdk/#deep-links
