### ISSUE TITLE
Campaign IDs not correctly decoded

### ISSUE THREAD

**Issue by nkotula** [Iterable/swift-sdk#296]
## Summary
Following up from the discussion over on the Android SDK side of things (see here: [https://github.com/Iterable/iterable-android-sdk/pull/223](https://github.com/Iterable/iterable-android-sdk/pull/223)), it would appear as though the Swift SDK is not adhering to the API contract that `campaignId` is a `long`.

When we receive an In-App message from a campaign, using an SSL proxy I can clearly see the `campaignId` coming over as a naked number, but the SDK is trying to decode it as a `String`.  I am confident this is causing all messages received to have empty campaign ID strings.  At least, it has been the case with all the messages I have tested with.

## Steps to Reproduce

1. Set up the SSL proxy for iOS simulators on your environment (if using Charles, see here for instructions: [https://www.detroitlabs.com/blog/2018/05/01/how-to-set-up-charles-proxy-for-an-ios-simulator/](https://www.detroitlabs.com/blog/2018/05/01/how-to-set-up-charles-proxy-for-an-ios-simulator/))
1. Ensure the SSL proxy is working by sending a proof to your developer account and observing the message JSON in your proxy.
1. Set up a breakpoint somewhere just before displaying the message so that the Iterable Swift SDK has parsed the JSON into an `IterableInAppMessage` object.
1. Create a campaign in app.iterable.com targeting one user (in our case, our mobile dev email)
1. Send the campaign and note the Campaign ID assigned to it from app.iterable.com.
1. Observe the received campaign message JSON has a numeric `clientId` via your proxy.
1. As soon as execution breaks at your breakpoint, inspect the received, decoded `IterableInAppMessage` object with Xcode.

- Expected Result:  The `IterableInAppMessage` `clientId` is correct.
- Actual Result:  The `IterableInAppMessage` `clientId` is always an empty string.

## Relevant Info
- SDK Version: `6.1.2`
  - Looking at the source, it doesn't look like the decoding logic has changed since this version to the latest stable version as of writing this.
- Mobile device: any iOS simulator with iOS ~10+~ 12+ <-- sorry about that confusion.
- SSL Proxy Tool: Charles

**Comment by tapashmajumder** [comment]
@nkotula Thanks for brining this to our attention. We will be working on this shortly.

**Comment by tapashmajumder** [comment]
@nkotula We have a PR pending for changes related to this. Please take a look if you are interested.

https://github.com/Iterable/swift-sdk/pull/297

**Comment by roninopf** [comment]
Thanks @nkotula , we've just released 6.2.5 which has this fixed. Thanks again for your report and diligence of the quality of the code! Feel free to open a new issue if one arises.
