### ISSUE TITLE
Internal class leakage

### ISSUE THREAD

**Issue by made2k** [Iterable/swift-sdk#320]
There are quite a few areas inside of `/swift-sdk/internal/` that leak into the public namespace. This causes naming conflicts when iterable is included with a project. One of the biggest and most common (as I can see) is the leak of Promise. These should probably be declared internal, or taken out of the internal directory and documented (though I feel this SDK should not provide tools such as these since it's not the focus of this SDK). Here's a list of files that have public declarations inside of the internal directory.

Promise.swift
Dwifft+UIKit.swift
IterableInboxImpression.swift
DateProvider.swift
AbstractDiffCalculator.swift
IterableActionRunner.swift
IterableUtil.swift

**Comment by roninopf** [comment]
Thanks for reporting! You're completely right, we'll prioritize a fix to make them internal. And you're also accurate on Promise. We intended it to just be used internally until Swift officially release their own version of it (which from my research seems to be near, there definitely are proposals for it).

**Comment by roninopf** [comment]
Hey @made2k , we've released 6.2.8 which includes the fix for this issue. Feel free to open a new issue if you run into something new. Thanks again for reporting.

**Comment by made2k** [comment]
Thanks for checking that out guys, really appreciate it!
