### ISSUE TITLE
Unrecognized selector exception on +updateSubscriptions...

### ISSUE THREAD

**Issue by paulbruneau** [Iterable/swift-sdk#324]
> +[IterableSDK.IterableAPI updateSubscriptions:unsubscribedChannelIds:unsubscribedMessageTypeIds:subscribedMessageTypeIds:campaignId:templateId:]: unrecognized selector sent to class 0x11311e040
(null)

Hey gang-- after updating to v6.2.4 (and the issue remains in 6.2.5), I am getting the crash above when I try to call the above method.

I note that recently you updated the name of this method to change the `campaignIds` parameter to `campaignId` which is fine, but although the header seems correct (and Xcode compiles my calling of its new name correctly), the method implementation seems not to be renamed (?)

This line of code below sets `responds` to `YES` telling me that perhaps the old declaration is still in the implementation. Note the `compaignIds` parameter with the `s` still on it like in the old versions:

BOOL responds = [IterableAPI respondsToSelector:@selector(updateSubscriptions:unsubscribedChannelIds:unsubscribedMessageTypeIds:subscribedMessageTypeIds:campaignIds:templateId:)];

I may be missing something really obvious, but could you have a quick look and see if you see anything that might explain my crash? Thank you.

**Comment by paulbruneau** [comment]
This is embarrassing but I have been informed that we may have two copies of the Iterable SDK in our project, which could be causing this. I wanted to let you know immediately while I investigate. I apologize in advance if this turns out to be the cause.

**Comment by roninopf** [comment]
No worries! Glad to know the issue might've been found! I've definitely run into similar setup accidents before. Feel free to keep this open in case it is a real issue.

**Comment by paulbruneau** [comment]
Thank you. I have verified that was our problem. For those interested, we had one copy in our main app, and another copy in a module. I have removed the second copy and changed the search paths to be able to point to the single copy to prevent such errors in the future. Closing issue.
