### ISSUE TITLE
Use of undeclared type UIDevice and UIUserInterfaceIdiom

### ISSUE THREAD

**Issue by schjonhaug** [Iterable/swift-sdk#328]
When adding Iterable using SPM, I get the following erros when trying to build:

* `Use of undeclared type 'UIUserInterfaceIdiom'`
* `Use of undeclared type 'UIDevice'`

Looks like UIKit import is missing?

I've attached a test project where I just added your package.

<img width="1281" alt="Skjermbilde 2020-05-27 kl  10 21 08" src="https://user-images.githubusercontent.com/84225/82995362-c9d8dc00-a003-11ea-9723-509f7fb03909.png">

[TestProject.zip](https://github.com/Iterable/swift-sdk/files/4687461/TestProject.zip)

**Comment by tapashmajumder** [comment]
Hi. You might be using an old version of our SDK. I see that we have `import UIKit` in our master branch.

**Comment by tapashmajumder** [comment]
https://github.com/Iterable/swift-sdk/blob/master/swift-sdk/Internal/DataFieldsHelper.swift

**Comment by tapashmajumder** [comment]
Please update the version of swift-sdk package you are using.

**Comment by schjonhaug** [comment]
My code is using version `6.2.7`, but it seems to be very far behind master in terms of commits, see https://github.com/Iterable/swift-sdk/releases/tag/6.2.7. Could you create a new version that has all the latest updates?

**Comment by tapashmajumder** [comment]
Ah. I see. Yes will do. Thanks!

**Comment by tapashmajumder** [comment]
In the meantime can you please build against `master` branch (instead of a version) just to check if everything is working?
![Screen Shot 2020-05-27 at 2 42 49 PM](https://user-images.githubusercontent.com/39278182/83000851-8d6ba700-a028-11ea-96c6-7ec4ab56d294.png)

**Comment by tapashmajumder** [comment]
This is just so that we know things are fine. We will be doing a new release soon.

**Comment by schjonhaug** [comment]
Yes, it works if I change to `master`. I'll wait for your update then, I prefer to use the versioning system, it gives more control than always getting the latest from master.

**Comment by tapashmajumder** [comment]
Thanks @schjonhaug  We have released a new version with the fix.
