### ISSUE TITLE
ios9 cannot run

### ISSUE THREAD

**Issue by a366376628** [Iterable/swift-sdk#352]
Hi
I see in the documentation that ios9 is supported
But when I added UNNotificationServiceExtension, it cannot run on ios9 devices.
I know that UNNotificationServiceExtension can only be run on devices after ios10, so the documentation does not lack the minimum version support instructions for UNNotificationServiceExtension? Still, there are some special settings for ios9 devices I haven't done right.

**Comment by a366376628** [comment]
when i use pods add Iterable-iOS-AppExtensions in ios9 
show "Specs satisfying the `Iterable-iOS-AppExtensions` dependency were found, but they required a higher minimum deployment target."
So to use this function, does the project have to support ios10 at least?

**Comment by roninopf** [comment]
Hi @a366376628, sorry I didn't see this before; but yes, `Iterable-iOS-AppExtensions` specifically requires iOS 10 (https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension).

You can have the Notification Service Extension target be iOS 10.0+ with the main app target being 9.0, but I'm not sure what the consequences of that is. I'm guessing that devices on iOS 9.0 that install your app probably don't get any of the bonuses of the service extension.

Hope that helps! Please feel free to open a new issue if one arises, or to file a ticket with us. Thanks!
