### ISSUE TITLE
isGhostPush bool no longer available

### ISSUE THREAD

**Issue by jtthrillson** [Iterable/swift-sdk#373]
We ignore ghost push notifications to prevent inaccurate data in our internal analytics, but after updating the SDK, getPushMetadata and its isGhostPush var aren't available. Has this been moved or is the only way to get this information parsing the payload manually?

**Comment by tapashmajumder** [comment]
Hi, It appears this structure is not public. Which SDK have you upgraded from? Are you using ObjC or Swift? Can you please have your customer service rep create a ticket for us with the relevant information?
Thanks!

**Comment by jtthrillson** [comment]
We're using Swift. We updated from version 6.0.10, where it was accessible:
```
let metadata = IterableNotificationMetadata.metadata(fromLaunchOptions: userInfo)
metadata.isGhostPush
```

**Comment by tapashmajumder** [comment]
Where are you getting the `launchOptions` from? I am trying to understand better how you are using this. Thanks!

**Comment by jtthrillson** [comment]
We use the payload from a push notification. The userInfo dictionary from:
`func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any])`

**Comment by tapashmajumder** [comment]
Hi. I have created a Jira ticket for this issue. Can you please let us know how urgent this is? So that we can prioritize accordingly. Also, which company do you work for? (So that we can tag the ticket with it).

**Comment by jtthrillson** [comment]
The issue is not immediately urgent, but important for keeping the dependency up to date. It would be helpful if it is addressed in the next month or so.
I work for UNiDAYS.
Thanks.

**Comment by tapashmajumder** [comment]
Thanks! We have created a ticket and will be working on this in a couple of weeks or so.

**Comment by roninopf** [comment]
Hi @jtthrillson, the latest release version `6.2.13` opens up `isGhostPush`; this should resolve this. If there are any new concerns, please feel free to open up another ticket/issue!
