### ISSUE TITLE
Unable to find a push integration set up for application xx on APNS_SANDBOX 

### ISSUE THREAD

**Issue by ir2pid** [Iterable/swift-sdk#384]
I get the below error on my xcode console when iterable is initialised with apns token.

`IterableAPIInternal:defaultOnFailure(identifier:):630: registerToken failed:, Unable to find a push integration set up for application xx on APNS_SANDBOX, got response {"msg":"Unable to find a push integration set up for application xx on APNS_SANDBOX","code":"BadParams","params":null}`

**Comment by tapashmajumder** [comment]
Hi. Please have your customer service representative open a support ticket with all relevant details and steps to repro this issue.

**Comment by tapashmajumder** [comment]
Please see notes above
