### ISSUE TITLE
'shared' is unavailable in application extensions for iOS

### ISSUE THREAD

**Issue by corban123** [Iterable/swift-sdk#400]
Attempting to use Iterable using a Sub-project (We have a main app, then a "Networking" app), however, when attempting to use Iterable, end up with the error 
`'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`

Was hoping for a fix

**Comment by tapashmajumder** [comment]
How are you including Iterable-iOS-SDK in your project? I mean whether you are using Cocoapods or SPM? Have you tried swift package manager?

**Comment by tapashmajumder** [comment]
Please see the solution provided here. 

https://stackoverflow.com/questions/56840374/iqkeyboardmanagerswift-shared-is-unavailable-use-view-controller-based-soluti/56841689

**Comment by corban123** [comment]
@tapashmajumder I'm using Cocoapods. 

I've seen warnings that if you set it to NO as per the stackoverflow link that you may be liable to have Apple reject your app.

**Comment by tapashmajumder** [comment]
Do you have any links regarding that? We have not heard about App Store rejection from anyone else.

**Comment by tapashmajumder** [comment]
We have not heard of any App Store rejection due to this. I am closing this issue. Please contact your Iterable customer service rep and open a Jira ticket if you run into any issue.
