### ISSUE TITLE
Iteratable Static framework

### ISSUE THREAD

**Issue by ukmunnithan** [Iterable/swift-sdk#401]
Is there any way to get static framework of Iteratable instead of dynamic.
My purpose is to create a static library including iteratable framework.
I could not able to use iteratable dynamic framewok. So please share the static framework

**Comment by tapashmajumder** [comment]
Yes. Please use Swift Package Manager. It is really simple and the recommended way to use our SDK.

Here is documentation.
https://support.iterable.com/hc/en-us/articles/360035018152#_2-1-install-the-sdk-with-the-swift-package-manager

**Comment by ukmunnithan** [comment]
@tapashmajumder my purpose is to create a static library by including the Iterable framework?
I tried a lot with the above mentioned link, but after it shows the error message as module IterableSDK not found.
Please help me to create a static library with static IterableSDK framework added in it?

**Comment by tapashmajumder** [comment]
Hi. Please have your customer service rep for Iterable open an a ticket with us.
That way we can look at the details of your case.
Thanks!
