### ISSUE TITLE
6.x Release SDKs binaries are missing simulator architectures

### ISSUE THREAD

**Issue by LeadAssimilator** [Iterable/swift-sdk#421]
The resulting fat universal binary is missing simulator architectures from all frameworks for the past couple of months:
```
IterableSDK: Mach-O universal binary with 2 architectures: [arm_v7:Mach-O dynamically linked shared library arm_v7] [arm64]
IterableSDK (for architecture armv7):   Mach-O dynamically linked shared library arm_v7
IterableSDK (for architecture arm64):   Mach-O 64-bit dynamically linked shared library arm64
```
Note the absence of i386 and x86_64.

scripts/build-target-module-framework.sh is failing to trap/check error codes and lipo is failing with: 
```
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: build/Release-iphonesimulator/IterableSDK.framework/IterableSDK and build/Release-iphoneos/IterableSDK.framework/IterableSDK have the same architectures (arm64) and can't be in the same fat output file
```

1. proper error checking should be added to all script commands
2. the xcodebuild commandline for iphonesimulator should have EXCLUDED_ARCHS="arm64" added to it
3. the frameworks should be converted to xcframeworks

2 should be quick temporary solution until 3 can be done and should only impact folks with DTK/arm64 mac who try to use the simulator.

3 would additionally address the issue with DTK/arm64 macs, but might have a larger impact on all the current consumers of the frameworks forcing them to upgrade their toolchains and adjust their projects etc.  

And of course both 2 and 3 could be done for maximum compatibility for some time, giving users a chance to migrate to the newer xcframework builds once available.

**Comment by roninopf** [comment]
Hi @LeadAssimilator! Thank you for this report; it's great timing as we've been working on this.

We'll be rolling out the new XCFramework versions first, but your noted concerns about giving people a chance to update their toolchains is what we're trying to accommodate for right now.

If you'd like to try our XCFrameworks (we're successfully generating them, and our internal testing has been successful as well), please let your CSM know and we can pass those along.

**Comment by roninopf** [comment]
Actually, I've gone ahead and attached the XCFrameworks for our [latest SDK release](https://github.com/Iterable/swift-sdk/releases/tag/6.2.15), as the precursor for future releases.

**Comment by roninopf** [comment]
Thanks again for your report; we've officially merged in our new SDK generation scripts. We didn't quite get to better error checking; we'll be doing that in a future task.

If you have another report to make, please feel free to open another issue here or with your CSM.
