### ISSUE TITLE
Mobile Inbox - In App message presentation style

### ISSUE THREAD

**Issue by skyfoxa** [Iterable/swift-sdk#434]
Hi, I'm working on Mobile Inbox feature for our app. I have issue with presentation style when user selects a message in the inbox. Can you make **setModalPresentationStyle(for viewController: UIViewController)** in **IterableInboxViewController** public or provide a way how to change the presentation style? I need to use `.overCurrentContext` value

**Comment by skyfoxa** [comment]
@bradumbaugh @sarkis @gmethvin @mzupan is there anybody who could take a look on this?

**Comment by roninopf** [comment]
Hi @skyfoxa! Sorry for the late response, we'll put this feature into our next sprint.

**Comment by roninopf** [comment]
@skyfoxa, we just released 6.2.19 which adds a new variable (`popupModalPresentationStyle`) where you can specify what transition to use instead.

Feel free to write in again if you run into a new issue!

**Comment by skyfoxa** [comment]
@roninopf Thank you, this works perfectly.
