### ISSUE TITLE
'shared' is unavailable: not available on iOS (App Extension) on Xcode 13 beta 3

### ISSUE THREAD

**Issue by paulmesa-paypal** [Iterable/swift-sdk#488]
Describe the bug
The package is not compiling on Xcode 13 beta 3, shows this error: 'shared' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead

Open your project using Xcode 13 beta 3
Clean project
Build Project
See error

Expected behavior:
Package compiles successfully

Versions
Xcode: 13.0 beta 3 (13A5192j)
Mac OS: 11.4
Library Version: 6.5.6

Additional context
There is a thread here https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/17 which explains the issue.

**Comment by paulmesa-paypal** [comment]
Here is an example fix in the braintree iOS sdk https://github.com/braintree/braintree_ios/commit/89912f4cc91cf8b715343623e9572b325cb949ac

**Comment by tapashmajumder** [comment]
Hi @paulmesa-paypal we officially do not support beta version of Xcode. We only support the latest released version of Xcode.

We will try to take a look at this if this is an easy fix.

**Comment by tapashmajumder** [comment]
Thank you for all the links provided.

**Comment by kylebrowning** [comment]
Here's the fix:

https://twitter.com/twannl/status/1415643866414338054

**Comment by paulmesa-paypal** [comment]
Understandable! @tapashmajumder I do have a fix up on a fork that we've been using for development here https://github.com/Iterable/swift-sdk/compare/master...paulmesa-paypal:pm/july/SteelThread but I havent verified any behavior outside of the small subset that we use

**Comment by kylebrowning** [comment]
Just want to reiterate up, this makes Xcode beta's impossible to use without removing Iterable entirely. 

I know that you dont support betas, but I just want to highlight that this means we can't work on features in coordination with Apple to launch along side the release of iOS 15. 

It is extremely debilitating to have to remove Iterable each time we need to work on an iOS 15 feature in anticipation of the launch.

**Comment by tapashmajumder** [comment]
@kylebrowning Can you please escalate this issue using your CSM for Iterable? Which company do you work for? 
This way we can prioritize this issue with urgency if needed.

**Comment by kylebrowning** [comment]
The Athletic. I'll raise a new support ticket, thanks.

**Comment by kylebrowning** [comment]
I opened a ticket but I havn't heard back. At any rate, it looks like Apple has reverted this change in Xcode Beta 5 and Iterable works again!

**Comment by tapashmajumder** [comment]
Good to hear this @kylebrowning . In the future if you open a ticket and get no response kindly have the item escalated via your CSM. This ticket did not get escalated to engineering. 

I will go ahead and close this issue.

**Comment by kylebrowning** [comment]
Well I wouldn't say this should be closed, Theres a very real chance you'll have to do this in the future.

**Comment by tapashmajumder** [comment]
OK. Keeping this open.

**Comment by tapashmajumder** [comment]
This issue should be resolved with SDK version 6.3.4
