### ISSUE TITLE
Could not find module 'IterableAppExtensions' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by tungfam** [Iterable/swift-sdk#498]
When running on a physical device, all works fine.
But when trying to run on simulator using M1 Apple Silicon processor and getting an error:
`Could not find module 'IterableAppExtensions' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator`

Xcode 12.5.1

Side note: my colleague runs on the same Xcode but with Intel processor and it works fine on the simulator.

**Comment by ken-brown** [comment]
Does this problem still occur with Xcode 13?

**Comment by tapashmajumder** [comment]
I am not seeing this issue on my M1 mac. Can you please contact your Iterable customer service rep and create a ticket for this with more details?

**Comment by tapashmajumder** [comment]
Should be fixed with version 6.4.2. Please open a ticket with your CSM if you are still seeing issues.
