### ISSUE TITLE
Warning: Could not find IterableDataModel.momd in bundle

### ISSUE THREAD

**Issue by duyenlv** [Iterable/swift-sdk#511]
Hi Iterable team, 

I am working to update Iterable iOS SDK version to Swift project, At version **6.3.4**, I encounter 2 warnings. 
Could you help to resolve them?   

> 2021-10-24 12:37:36.302653+0700 TiffsTreats[70452:6048708] ❤️ 12:37:36.3020:0x283194800:IterableCoreDataPersistence:createManagedObjectModel(fromBundle:):64: Could not find IterableDataModel.momd in bundle
> 2021-10-24 12:37:36.302883+0700 TiffsTreats[70452:6048708] ❤️ 12:37:36.3030:0x283194800:IterableCoreDataPersistence:create(fromBundle:):44: Could not initialize managed object model

Our swift project uses Cocoapods.

**Comment by tapashmajumder** [comment]
Closed since the problem is solved.
