### ISSUE TITLE
Callback after in-app messages have finished displaying, even if there are no in-app messages

### ISSUE THREAD

**Issue by vrutberg** [Iterable/swift-sdk#52]
Hi,

I'm working to integrate this SDK in our app and I would like to have some more fine-grained feedback from the SDK on when in-app messages have finished displaying.

My use-case is this: We have a series of modal pop-ups in the app that may or may not display when the user logs in. We want to avoid displaying these modal pop-ups on top of each other, so each modal fires a callback when it is "done". It does this in two cases:

1. It doesn't need displaying
2. It has displayed, and the user has closed it

I would like to have the same functionality for Iterable in-app messages.

The documentation for release `6.0.6` says this:

> To display the user's InApp notifications call spawnInAppNotification with a defined ITEActionBlock callback handler. When a user clicks a button on the notification, the defined handler is called and passed the action name defined in the InApp template.

A suggestion would be for this callback to be called *even if there are no in-app messages to display*. That way I know that when the callback has been called it is safe to continue displaying other modal pop-ups to the user.

I've seen that you're in the process of reworking how in-app messages work on the `master` branch, so I would like for your new solution to be able to solve my use-case.

**Comment by tapashmajumder** [comment]
We are currently working on a big revamp of in-app messages. Please check out the 'in-app messages' section of README.md for new changes to in-app.

We are ready to roll out a beta version of in-app messages which will take care of this and much more. Would you be interested in that?

**Comment by vrutberg** [comment]
Yeah, that would be great. How do I access the beta version?

**Comment by tapashmajumder** [comment]
@vrutberg Use tag 6.1.0-beta1 from Github in your app. Sample Podfile is below

```Podfile
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'iOS Demo' do
  pod 'Iterable-iOS-SDK', :git => 'https://github.com/Iterable/swift-sdk.git', :tag => '6.1.0-beta1'

  target 'iOS DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end

target 'richMediaAttachments' do
    pod 'Iterable-iOS-AppExtensions', :git => 'https://github.com/Iterable/swift-sdk.git', :tag => '6.1.0-beta1'
end

```

**Comment by tapashmajumder** [comment]
@vrutberg If you send me your email address to tapash at iterable dot com I can add you to our Slack channel for beta feedback etc.

**Comment by vrutberg** [comment]
Great. I'm using Carthage but the setup should be similar. I will try it out and keep you posted!

**Comment by vrutberg** [comment]
Migrating to the beta version seems quite straight-forward. Just as a sanity check, could you verify that this method of displaying in-app messages looks good to you?

```swift
func displayInAppMessages(completionHandler: @escaping () -> Void) {
    let messages = IterableAPI.inAppManager.getMessages()

    guard let first = messages.first else {
        completionHandler()
        return
    }

    IterableAPI.inAppManager.show(message: first, consume: true, callback: { _ in
        completionHandler()
    })
}
```

The idea is that we want to show one in-app message at a time. Please note that I'm also setting the `inAppDelegate` on the `IterableConfig` object and returning `.skip` in its delegate method.

**Comment by tapashmajumder** [comment]
Yes this looks great.

You may also want to consider using IterableCustomActionDelegate or IterableURLDelegate to handle clicks in your in-app instead of the completionHandler. See here https://github.com/iterable/swift-sdk#when-user-clicks-a-buttonlink-in-the-in-app-message

**Comment by vrutberg** [comment]
Great! Alright, thanks for the tip. I will look into that.

Do you have any expected release date for the new version?

**Comment by tapashmajumder** [comment]
Depends on whether we find any serious bugs in our beta. Hopefully in a few weeks.

**Comment by tapashmajumder** [comment]
I am going to close this issue now since it is taken care of in the beta release.
