### ISSUE TITLE
Version 6.4.0 fails to compile when archiving

### ISSUE THREAD

**Issue by jbelkins** [Iterable/swift-sdk#523]
I am running Xcode 13.2 on both CI and on desktop.

When archiving my app with Iterable iOS SDK version 6.4.0 integrated using Swift Package Manager, either in CI or on desktop, I get the following compile errors (these errors were generated on CircleCI):
```
❌  /Users/distiller/project/Packages/checkouts/swift-sdk/swift-sdk/swiftui/InboxViewRepresentable.swift:22:40: cannot find type 'Context' in scope

    func makeUIViewController(context: Context) -> IterableInboxViewController {
                                  ^~~~~

❌  /Users/distiller/project/Packages/checkouts/swift-sdk/swift-sdk/swiftui/InboxViewRepresentable.swift:34:91: cannot find type 'Context' in scope

    func updateUIViewController(_ uiViewController: IterableInboxViewController, context: Context) {
                                       ^~~~~~~

❌  /Users/distiller/project/Packages/checkouts/swift-sdk/swift-sdk/swiftui/InboxViewRepresentable.swift:11:32: cannot find type 'UIViewControllerRepresentable' in scope

struct InboxViewRepresentable: UIViewControllerRepresentable {
                                                                                          ^~~~~~~

❌  /Users/distiller/project/Packages/checkouts/swift-sdk/swift-sdk/swiftui/IterableInboxView.swift:73:27: cannot find type 'View' in scope

    public var body: some View {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

❌  /Users/distiller/project/Packages/checkouts/swift-sdk/swift-sdk/swiftui/IterableInboxView.swift:11:34: cannot find type 'View' in scope

public struct IterableInboxView: View {
                          ^~~~
```

When not archiving (i.e. building on desktop or running tests on CI) the Iterable SDK builds correctly.
In the interim, I have rolled back to a previous version of the Iterable SDK to complete my build.

Please investigate.

**Comment by jbelkins** [comment]
I get the same compile errors when building the `IterableSDK` target in this project with "Release" as the selected build configuration.  So that pretty much rules out any config on my end as a cause.

**Comment by tapashmajumder** [comment]
@jbelkins 
Thank you so much for bringing this up.
Would you be able to try the following branch and let us know if this worked? 

Branch
`tapash/fix-archive-issue`

**Comment by jbelkins** [comment]
@tapashmajumder The branch you provided seems to fix the issue.

**Comment by tapashmajumder** [comment]
👍

**Comment by tapashmajumder** [comment]
Should be fixed with release 6.4.1. Closing.

**Comment by iosdevben** [comment]
I'm getting the same issue with release 6.4.1 if I have my scheme set to build in release mode.

**Comment by iosdevben** [comment]
> I get the same compile errors when building the `IterableSDK` target in this project with "Release" as the selected build configuration. So that pretty much rules out any config on my end as a cause.

Same
