### ISSUE TITLE
is there a way to have access to getInAppShowingWaitTimeInterval value?

### ISSUE THREAD

**Issue by elanovasconcelos** [Iterable/swift-sdk#533]
is there a way to have access to getInAppShowingWaitTimeInterval value? I need this value, but I couldn't find a way to get it

**Comment by tapashmajumder** [comment]
Sorry this is a private value. Can you please explain why you need access to this?

**Comment by elanovasconcelos** [comment]
There are some moments that I start or stop showing messages, but I need a way to know if it's ok to show again messages respecting the retryInterval.

another question: is there a way to dismiss the current message (IterableInAppHTMLViewController) by code?

**Comment by tapashmajumder** [comment]
Hi @elanovasconcelos It will be unidiomatic for us to provide access to this value. This is used internally to schedule next in-app message. If you want to show an in-app manually then you can just show it anytime and don't need to worry about the retry interval.

No, currently there is no way to dismiss the current message by code? Are you thinking about a message that stays on the screen for sometime and then disappears after that? Maybe that is something we can look at in the future.

**Comment by roninopf** [comment]
Closing due to age, if you feel that this is a relevant issue, I actually suggest letting your CSM know that this in particular is a feature request. Thanks!
