### ISSUE TITLE
6.4.1 fails to build with scheme set to use release configuration for build

### ISSUE THREAD

**Issue by iosdevben** [Iterable/swift-sdk#538]
I created a new Xcode 13.2.1 project, added the Iterable 6.4.1 package, set my scheme to use the release configuration for builds, and get the following errors when compiling:

> /Users/benthomas/Library/Developer/Xcode/DerivedData/ReleaseThis-fomtdjahcddcdtbgpfqiparxlozy/SourcePackages/checkouts/swift-sdk/swift-sdk/swiftui/InboxViewRepresentable.swift:22:40: error: cannot find type 'Context' in scope
>     func makeUIViewController(context: Context) -> IterableInboxViewController {
>                                        ^~~~~~~
> /Users/benthomas/Library/Developer/Xcode/DerivedData/ReleaseThis-fomtdjahcddcdtbgpfqiparxlozy/SourcePackages/checkouts/swift-sdk/swift-sdk/swiftui/InboxViewRepresentable.swift:34:91: error: cannot find type 'Context' in scope
>     func updateUIViewController(_ uiViewController: IterableInboxViewController, context: Context) {
>                                                                                           ^~~~~~~
> /Users/benthomas/Library/Developer/Xcode/DerivedData/ReleaseThis-fomtdjahcddcdtbgpfqiparxlozy/SourcePackages/checkouts/swift-sdk/swift-sdk/swiftui/InboxViewRepresentable.swift:11:32: error: cannot find type 'UIViewControllerRepresentable' in scope
> struct InboxViewRepresentable: UIViewControllerRepresentable {
>                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /Users/benthomas/Library/Developer/Xcode/DerivedData/ReleaseThis-fomtdjahcddcdtbgpfqiparxlozy/SourcePackages/checkouts/swift-sdk/swift-sdk/swiftui/IterableInboxView.swift:73:27: error: cannot find type 'View' in scope
>     public var body: some View {
>                           ^~~~
> /Users/benthomas/Library/Developer/Xcode/DerivedData/ReleaseThis-fomtdjahcddcdtbgpfqiparxlozy/SourcePackages/checkouts/swift-sdk/swift-sdk/swiftui/IterableInboxView.swift:11:34: error: cannot find type 'View' in scope
> public struct IterableInboxView: View {
>                                  ^~~~
>

**Comment by iAmrSalman-ibm** [comment]
I'm facing the same issue, when building using any configurations besides Debug I see those errors

**Comment by tapashmajumder** [comment]
Should be fixed with version 6.4.2. Please open a ticket with your CSM if you are still seeing issues.
