### ISSUE TITLE
WebP Rich Media Support

### ISSUE THREAD

**Issue by Grimlock257** [Iterable/swift-sdk#552]
I've noticed when using a iOS rich media URL that refers to a `webp` image, the attachment is not shown as part of the notification, however the URL is correctly pulled down in `attachment-url` when printing the push payload to the XCode console, and changing the format of the image from `webp` to `png` (for example) works and is displayed as expected.

Is `webp` rich media a supported use case, if not, are there any plans or ETAs on when this would be supported? We'd like to use WebP as the file sizes for our use case are a lot smaller 😄 

Thanks!

**Comment by jacao** [comment]
+1
