### ISSUE TITLE
Objective-C modules are incompatible with Objective-C++ (React Native 0.68+)

### ISSUE THREAD

**Issue by shamilovtim** [Iterable/swift-sdk#563]
The Iterable docs recommending using the `@import` Objective-C module syntax:
<img width="759" alt="Screen Shot 2022-06-14 at 7 28 04 PM" src="https://user-images.githubusercontent.com/3495974/173705741-496d05d8-32bc-4463-931e-53aa0be05a08.png">

Unfortunately, this is not compatible with Objective-C++ (React Native 0.68+):
<img width="778" alt="Screen Shot 2022-06-14 at 7 29 37 PM" src="https://user-images.githubusercontent.com/3495974/173705826-3e3c588c-4c5c-40e4-8dce-6940404718ed.png">

Please provide us with the headers we can import instead of the module syntax.

Related:
https://github.com/firebase/FirebaseUI-iOS/issues/875
https://github.com/facebook/react-native/issues/33692
https://github.com/invertase/react-native-firebase/pull/6223
https://github.com/segmentio/analytics-ios/issues/1036

**Comment by roninopf** [comment]
Thanks for reporting this @shamilovtim ! This screen shot is helpful. I'll be working on this ASAP.

**Comment by roninopf** [comment]
We've detailed a workaround fix in our docs by adding in a header file, for versions 0.68.2 to 0.69.3; versions 0.69.4+ have this issue fixed.
