### ISSUE TITLE
Iterable SDK freezes the app by using too many threads on a Global Queue

### ISSUE THREAD

**Issue by leolobato** [Iterable/swift-sdk#564]
# Summary

The most frequent crash we have on our app right now is related to the Iterable SDK queuing too many blocks on a Global Dispatch Queue, which freezes the app when any part of the code tries to use a Global Dispatch Queue on the main thread.

If Iterable SDK was using its own private queue (using `DispatchQueue(label:target:)` instead of `DispatchQueue.global()`), the app wouldn't crash.

# The Issue

Any global queue can create up to 64 threads simultaneously. If there are 64 threads from global queues active, no new threads will be scheduled until one of them is completed:

- https://stackoverflow.com/questions/15150308/workaround-on-the-threads-limit-in-grand-central-dispatch/15150800#15150800
- https://stackoverflow.com/a/69987248/67397

On the attached crash report, you can see:

[redacted-crash-report.txt](https://github.com/Iterable/swift-sdk/files/8906521/redacted-crash-report.txt)

- There are exactly 64 threads from a global dispatch queue (they are named `com.apple.root.default-qos`)
- From those, 58 are from the Iterable SDK -- Thread 1 and from Threads 11 to 68
- Then there are 5 threads from our own app (Threads 71 to 76)

On the main thread (Thread 0), another SDK is doing a synchronous call to a global dispatch queue to synchronize access to a property. On that moment, because all the 64 threads from a global queue are already "taken", the main thread will freeze waiting for them to complete and the iOS watchdog will kill the app after 10 seconds.

# Proposed solution

There is a really comprehensive writeup here on good practice when using GCD: https://gist.github.com/tclementdev/6af616354912b0347cdf6db159c37057

The key point for this issue (thread explosion) is:

> Don't use `DispatchQueue.global()`. Global queues easily lead to thread explosion: threads blocking on sleeps/waits/locks are considered inactive by the libdispatch which in turn will spawn new threads when other parts of your program dispatch. Note that it is impossible to guarantee that your threads are never going to block, as merely using the system libraries will cause it to happen. Global queues also do not play nice with qos/priorities. The libdispatch maintainer at Apple declared it "the worst thing that the dispatch API provides". Run your code on one of your custom queue instead (one of your well-defined execution context).

So on `IterableTaskRunner.swift`, instead of using `DispatchQueue.global()`, you could reference a private queue that was created using `DispatchQueue(label:target:)` and let all your tasks run on that queue.

So if any other part of the app tries to use a global dispatch queue, it will not be affected by the thread explosion inside Iterable.

**Comment by tapashmajumder** [comment]
Hi @leolobato Thank you so much for the detailed report. 
This problem should be fixed with iOS SDK version `6.4.4`. Can you please check which version of iOS SDK the app is using during the crash report.

**Comment by tapashmajumder** [comment]
Hi @leolobato you have a very valid question. The reason 6.4.4 will solve the threading problem is because now all scheduling work by it will be done under one persistence context in one thread. All scheduling done in IterableTaskScheduler is under `persistenceContext.perform`. Earlier every request was being handled by a separate thread.

The DispatchQueue.global() call that there is just for scheduling the next call. It does not do the actual work. So should not cause a thread explosion. 
 
Having said that, using abundance of caution, I agree that it is better to do `DispatchQueue(label:target:)` instead of 'DispatchQueue.global()`. We will fix that in the next version. But this version should fix the crash that you are seeing.

**Comment by leolobato** [comment]
Perfect. Thank you for the detailed explanation, @tapashmajumder !

In that case, I will close this issue and let you know in case we run into any problems after the update.
