### ISSUE TITLE
handle(universalLink) does not behave as described. 

### ISSUE THREAD

**Issue by scottasoutherland** [Iterable/swift-sdk#592]
We upgrade from version 6.3.4 to version 6.4.9 of the Iterable SDK, and we ran into an issue where our deeplink routes are being routed twice. 

It was discovered that the reason for this is the call to "handle(universalLink url: URL)" is now returning false where it used to return true for the same deeplink. 

Upon closer examination, the reason seems to be that as per the documentation on this function, it says `Returns: true if it is an Iterable link, or the value returned from IterableURLDelegate otherwise`. However, the call makes it through to the URL Delegate, which returns true. But the call to handle(universalLink url: URL) returns false. This seems to be because the call inside DeepLinkManager-> handleUniversalLink went from this:
    
![Screenshot 2023-02-22 at 11 21 41 AM](https://user-images.githubusercontent.com/48388/220736695-8a34b50c-5f45-4046-a775-843b0409f298.png)

to this
    
![Screenshot 2023-02-22 at 11 22 10 AM](https://user-images.githubusercontent.com/48388/220736808-ac58f3a3-2f2d-4bad-ab79-0428f1bb45d3.png)

As you can see it is no longer capturing the result from ActionRunner.execute and always returns `false` no matter what the URLDelegate returns.

**Comment by jonasman** [comment]
Any update here? this is a problem here also

@Ayyanchira

**Comment by scottasoutherland** [comment]
Here is a pull request for this issue: https://github.com/Iterable/swift-sdk/pull/795
