### ISSUE TITLE
If initial JWT token request fails, SDK doesn't ever request a new one

### ISSUE THREAD

**Issue by aboatti** [Iterable/swift-sdk#594]
<img width="1115" alt="Screen Shot 2023-03-01 at 2 10 05 PM" src="https://user-images.githubusercontent.com/979738/222240353-1fc338c6-07f5-4d70-85ea-edc20dd02ce4.png">

Suggest you request a new token in the else of this guard statement

**Comment by Ayyanchira** [comment]
Thanks for suggestion @aboatti . 
We are considering this to be included in upcoming releases ...

**Comment by roninopf** [comment]
Hi @aboatti, we've released version 6.4.12 which has this suggestion implemented, thank you for writing in! Please feel free to write in to your CSM or create a new issue if something comes up.
