### ISSUE TITLE
6.4.12 contains semver-breaking API change

### ISSUE THREAD

**Issue by dpogue** [Iterable/swift-sdk#615]
The addition of `onTokenRegistrationFailed ` to `IterableAuthDelegate` changes the API such that existing code is no longer correct, which should require a bump to the major version number under semantic versioning rules. It is unexpected that a patch-version update would break existing code.

From the build logs for our Iterable integration code:
```
ios/Plugin/IterablePlugin.swift:185:1: error: type 'IterablePlugin' does not conform to protocol 'IterableAuthDelegate'
extension IterablePlugin : IterableAuthDelegate {
^

ios/Plugin/IterablePlugin.swift:185:1: note: do you want to add protocol stubs?
extension IterablePlugin : IterableAuthDelegate {
^
```

**Comment by roninopf** [comment]
Hi @dpogue, thanks for writing in. I apologize in advance, but we currently don't follow semver rules for a couple of internal reasons, however, I know I personally would like to be able to do so in the future.

Sorry for the inconvenience and error notification. At least, at a minimum, that function can be left empty.

**Comment by dozoisch** [comment]
@roninopf might be good to remove this line https://github.com/Iterable/swift-sdk/blob/a99ecf38f7bacc9b5ac9c8b13a3d7ec1b43d3124/CHANGELOG.md?plain=1#L4 

This should help avoid confusion 

<img width="575" alt="image" src="https://github.com/Iterable/swift-sdk/assets/4422516/59356f39-a2bf-4c54-9d53-8c28af142510">
