### ISSUE TITLE
Type 'ReactIterableAPI' does not conform to protocol 'IterableAuthDelegate'

### ISSUE THREAD

**Issue by sreedhu-7** [Iterable/swift-sdk#616]
/node_modules/@iterable/react-native-sdk/ios/RNIterableAPI/ReactIterableAPI.swift:651:1 Type 'ReactIterableAPI' does not conform to protocol 'IterableAuthDelegate'

**Comment by roninopf** [comment]
Hi @sreedhu-7, this has been fixed in the React Native SDK release of 1.3.12. Thanks.
