### ISSUE TITLE
Crash in RequestHandler.swift with InternalIterableAPI Initialization

### ISSUE THREAD

**Issue by polurezov8** [Iterable/swift-sdk#681]
### **Description**:
Our application, utilizing version **6.4.15** of the Iterable iOS SDK, consistently experiences crashes. 
The stack trace identifies `RequestHandler.swift` as the origin during the `InternalIterableAPI` initialization process.

### **Expected Behavior**:
* The `InternalIterableAPI` should initialize seamlessly without causing the application to crash.

### **Actual Behavior**:
* The application crashes when initializing `InternalIterableAPI` using SDK version **6.4.15**.

### **Stack Trace**:
```
Crashed: com.apple.root.user-initiated-qos.cooperative
0  libobjc.A.dylib                0x2c00 objc_retain + 16
1  libobjc.A.dylib                0x2c00 objc_retain_x0 + 16
2  App                            0x27fed8 specialized DependencyContainerProtocol.createRequestHandler(apiKey:config:endpoint:authProvider:authManager:deviceMetadata:offlineMode:) + 4313890520 (RequestHandler.swift:4313890520)
3  App                            0x27cfac closure #1 in InternalIterableAPI.requestHandler.getter + 66 (ClassExtensions.swift:66)
4  App                            0x27b26c InternalIterableAPI.inAppManager.getter + 4313870956
5  App                            0x27b050 closure #1 in InternalIterableAPI.inAppManager.getter + 77 (InternalIterableAPI.swift:77)
6  App                            0x27b26c InternalIterableAPI.inAppManager.getter + 4313870956
7  App                            0x27d828 InternalIterableAPI.start() + 635 (InternalIterableAPI.swift:635)
8  App                            0x2cb558 specialized static IterableAPI.initialize2(apiKey:launchOptions:config:apiEndPointOverride:callback:) + 123 (IterableAPI.swift:123)
9  App                            0x9d88c4 closure #1 in static IterableNotificationsClient.liveValue.getter + 29 (IterableNotificationsClient.swift:29)
10 libswift_Concurrency.dylib     0x41c2c swift::runJobInEstablishedExecutorContext(swift::Job*) + 416
11 libswift_Concurrency.dylib     0x42e88 swift_job_runImpl(swift::Job*, swift::ExecutorRef) + 72
12 libdispatch.dylib              0x15be4 _dispatch_root_queue_drain + 392
13 libdispatch.dylib              0x163ec _dispatch_worker_thread2 + 156
14 libsystem_pthread.dylib        0x1928 _pthread_wqthread + 228
15 libsystem_pthread.dylib        0x1a04 start_wqthread + 8
```

One more stack trace:
```
Crashed: com.apple.root.user-initiated-qos.cooperative
0  libobjc.A.dylib                0x3a7c objc_retain + 16
1  libobjc.A.dylib                0x3a7c objc_retain_x0 + 16
2  App                            0x27fed8 specialized DependencyContainerProtocol.createRequestHandler(apiKey:config:endpoint:authProvider:authManager:deviceMetadata:offlineMode:) + 4374707928 (RequestHandler.swift:4374707928)
3  App                            0x27cfac closure #1 in InternalIterableAPI.requestHandler.getter + 66 (ClassExtensions.swift:66)
4  App                            0x27b26c InternalIterableAPI.inAppManager.getter + 4374688364
5  App                            0x2c92c8 static IterableAPI.updateUser(_:mergeNestedObjects:onSuccess:onFailure:) + 239 (InternalIterableAPI.swift:239)
6  App                            0x2e2f60 closure #3 in static IterableTrackingClient.liveValue.getter + 17 (LiveIterableTrackingClient.swift:17)
7  libswift_Concurrency.dylib     0x41948 swift::runJobInEstablishedExecutorContext(swift::Job*) + 416
8  libswift_Concurrency.dylib     0x42868 swift_job_runImpl(swift::Job*, swift::ExecutorRef) + 72
9  libdispatch.dylib              0x15944 _dispatch_root_queue_drain + 396
10 libdispatch.dylib              0x16158 _dispatch_worker_thread2 + 164
11 libsystem_pthread.dylib        0xda0 _pthread_wqthread + 228
12 libsystem_pthread.dylib        0xb7c start_wqthread + 8
```

I eagerly await your reply and suggestions for resolving this issue. Your assistance is highly appreciated as we aim to ensure a smooth experience for our users.

Thank you for your attention to this matter.

**Comment by polurezov8** [comment]
## Issue Summary

From the provided Swift code, it appears that the crash is related to the `createRequestHandler` method, which is an integral part of your dependency injection system. The root cause of the crash likely pertains to how the `DependencyContainerProtocol` is creating and managing objects.

## Investigation Steps

To address and potentially resolve this issue, consider the following steps:

1. **Review the `createRequestHandler` Method:** Take a closer look at the `createRequestHandler` method in the `DependencyContainerProtocol` to ensure that it correctly initializes objects and manages memory. Verify that object creation is error-free and adheres to best practices.

2. **Check for Unwrapped Optionals:** Check for any optional values within the `createRequestHandler` method that may not be properly unwrapped, potentially causing unexpected crashes. Ensure that optionals are handled safely.

3. **Examine Object Lifecycle:** Investigate the lifecycle of objects created within this method. Ensure that objects are retained and released appropriately to prevent memory leaks and crashes.

4. **Review Dependencies:** Examine any dependencies that the `createRequestHandler` method relies on. Confirm that these dependencies are correctly configured and initialized. Ensure that dependencies are available when needed.

5. **Error Handling and Logging:** Consider adding robust error handling and logging mechanisms to the `createRequestHandler` method. Detailed error messages and logs can provide valuable insights into the root cause of the crashes.

## Conclusion

It is crucial to conduct a thorough investigation of the code within the `createRequestHandler` method and its associated dependencies. Identifying the precise cause of the crashes is essential for effective troubleshooting. Additionally, a review of recent changes in the Swift code related to memory management and object creation may help pinpoint the issue.

Your attention to these steps will greatly assist in resolving the problem and improving the stability of the application.

Please let me know if you require any further assistance or have additional information to provide.

**Comment by m-yeroshenko** [comment]
I'd like to draw attention to this issue because it also affects the application I'm working on. 
Such crash has a substantial negative impact on user satisfaction with our app. 
My team is eager to find a solution to address this problem as we want to provide the best possible user experience. 

Thank you in advance for your efforts in addressing this matter!

**Comment by polurezov8** [comment]
@jena-chakour Hi! Any developments on this issue? 
We're experiencing a -3% impact on our crash-free rating due to this bug.

**Comment by jyu115** [comment]
hi @polurezov8 @m-yeroshenko, we are looking into this issue. If possible, can I get more details about the devices on which the crash happens?

**Comment by polurezov8** [comment]
Hi @jyu115!
Devices:
98% - iPhone
2% - iPad

iOS Version:
53% - iOS 17
43% - iOS 16
2% - iOS 15
2% - other

This issue has 2,827 crash events affecting 2,392 users last week and it's critical for us.

**Comment by m-yeroshenko** [comment]
@jena-chakour Hi! 
Are there any updates about this issue? 
Would be great to find a solution ASAP

**Comment by jena-chakour** [comment]
Hi all @m-yeroshenko @ @polurezov8! Appreciate your patience while we work on this. We've not been able to replicate the crash so far, so I've reached out to Olena for more recent test cases

**Comment by hardikmashru** [comment]
@m-yeroshenko Are you getting these crashes in the debug environment too?

**Comment by m-yeroshenko** [comment]
Hi all! 
@hardikmashru Compared to the production environment, we have a significantly lower number of sessions. However, as far as I know, we haven't observed this crash in our debug builds. Additionally, I attempted to reproduce the issue in the debug build on iOS 15.8, 16.0, and 17.2 following your question, but I couldn't replicate it.

**Comment by polurezov8** [comment]
@hardikmashru @jena-chakour @jyu115 
Any updates here?
