### ISSUE TITLE
Xcode 16 beta 2 throws error stating Type 'WKWebView' does not conform to protocol 'WebViewProtocol'

### ISSUE THREAD

**Issue by harish-suthar** [Iterable/swift-sdk#777]
**Xcode 16 beta 2 throws error stating Type 'WKWebView' does not conform to protocol 'WebViewProtocol'**

<img width="1728" alt="Screenshot 2024-06-26 at 5 29 48 AM" src="https://github.com/Iterable/swift-sdk/assets/91060750/401595ff-9e0f-483c-b6b4-45aead4a40a5">

**Comment by harish-suthar** [comment]
<img width="1724" alt="Screenshot 2024-06-26 at 5 21 47 PM" src="https://github.com/Iterable/swift-sdk/assets/91060750/4ac183a6-38fa-4b93-a5a4-197c6d18a6df">

Adding the blank method implementation using protocol extension solved the issue temporary, but this is doable only if I use cocoapods with SPM we can't update the source code so.

**Comment by mtzaquia** [comment]
As @harish-suthar mentioned, if modifying the files is an option (I do not see this updated on 6.5.3, which is the latest release available), simply adding `@MainActor` to the function should suffice:

```
protocol WebViewProtocol {
    var view: UIView { get }
    var position: ViewPosition { get }
    @discardableResult func loadHTMLString(_ string: String, baseURL: URL?) -> WKNavigation?
    func set(position: ViewPosition)
    func set(navigationDelegate: WKNavigationDelegate?)
    func evaluateJavaScript(_ javaScriptString: String, completionHandler: (@MainActor (Any?, Error?) -> Void)?) // <- HERE
    func layoutSubviews()
    func calculateHeight() -> Future<CGFloat, IterableError>
}
```

This lets you move forward without extensions.

Curiously enough, I get this error even if using `@preconcurrency import IterableSDK`, so I am unsure if there's another way to suppress it without SDK code changes.

**Comment by Ayyanchira** [comment]
Thank you for reporting @harish-suthar and for the suggestions @mtzaquia . We will have this updated.

**Comment by Lancelotbronner** [comment]
Just to highlight the importance of this issue, since we can't use previous versions of Xcode on Sequoia, any developers updating to the beta will no longer be able to build their apps unless forking.

**Comment by powellmark-aceable** [comment]
Any update here? I'm currently blocked.

**Comment by JonLz** [comment]
We are blocked as well and would appreciate an update! Hopefully it is straightforward enough and could warrant a patch release. Thanks.

**Comment by jmonroe** [comment]
I am also blocked on this and reported it to Iterable.

**Comment by jena-chakour** [comment]
Hey all, quick note that the Iterable team is looking into this. We will update asap; appreciate everyone's feedback on the issue-- let us know if any relevant changes or details come up
