### ISSUE TITLE
v6.0.8 release only compiles when targeting device platform (not simulators)

### ISSUE THREAD

**Issue by irtemed88** [Iterable/swift-sdk#79]
I upgraded my version of Iterable from v6.0.6 to v6.0.8 and found the newest version wasn't compiling when targeting the iOS simulator. The error message Xcode provides is a bit misleading indicating the compiler can't find any symbols that are part of Iterable's SDK.

After investigation, in v6.0.8 each framework's `*-Swift.h` file only the device platform is targeted (there's an `elif defined(...)` at the top where this occurs). I'm not sure if this is a regression related to Iterable's release process or something with Xcode 10.2's build system.

It looks like this might at least be partially due to a known issue when building with Xcode 10.2. Apple has instructions for a workaround where each target should be built separately and then the headers combined using an `#ifdef` preprocessor: https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes#3136806

To test a fix, I built Iterable's SDK from source and used a `run script` build phase with `lipo` to merge the simulator and device frameworks into a single fat framework. Instructions for doing this can be found here: https://www.tirupatibalan.com/2019/01/05/create-fat-framework.html

The `run script` phase outlined in the link above for generating the fat framework isn't sufficient to handle the workaround necessary for Xcode 10.2 so I added an additional step that merges the two framework swift headers (it's not pretty but it works):
```
# 9
# Workaround for known issue in Xcode 10.2: https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes#3136806
# Merge the simulator and device headers for the now-merged framework.
HEADER_PATH="${OUTPUT_DIR}/${FRAMEWORK_NAME}.framework/Headers/${FRAMEWORK_NAME}-Swift.h"
rm "${HEADER_PATH}"
echo "#if TARGET_OS_SIMULATOR" >> "${HEADER_PATH}"
cat "${OUTPUT_DIR}/Build/Products/Release-iphonesimulator/${FRAMEWORK_NAME}.framework/Headers/${FRAMEWORK_NAME}-Swift.h" >> "${HEADER_PATH}"
echo "#else" >> "${HEADER_PATH}"
cat "${OUTPUT_DIR}/Build/Products/Release-iphoneos/${FRAMEWORK_NAME}.framework/Headers/${FRAMEWORK_NAME}-Swift.h" >> "${HEADER_PATH}"
echo "#endif" >> "${HEADER_PATH}"
```

I tested my solution in a sample application and both platforms built successfully. Since the application contains x86 and i386 architectures any application consuming the framework will need to strip these before submission (the link above has instructions for doing that as well).

Would it be possible to release the latest version of the framework as a fat framework using the approach outlined above?

**Comment by tapashmajumder** [comment]
Thanks for bringing this to our attention. We will take a look ASAP.

**Comment by tapashmajumder** [comment]
I don't seem to be having any issues with it. Can you please list steps to repro? How are just dragging and dropping the file from `releases` or are you using Cocoapods/Carthage?. If possible, please include your sample app.

**Comment by tolgaarikan** [comment]
Hey @tapashmajumder, we have the same problem. Yes, we are adding framework files from releases directly to our project. Sorry, I really don't have time for creating a sample app but this problem is keeping us from updating to swift 5, would really appreciate a fix.

**Comment by tapashmajumder** [comment]
Hi @tolgaarikan I have added new zip files to the 6.0.8 release yesterday (2019-04-23). Can you please try those and let us know if it worked?
Also, I understand that you may not have time to create sample project. Can you please copy/paste or attach screenshot of error you are seeing? Thanks!

**Comment by ArtemMysik** [comment]
Hi @tapashmajumder, I work with @tolgaarikan . We use .framework. The error when building for simulator: `Cannot find protocol declaration for 'IterableURLDelegate'` in **ProjectName-Swift.h** file

**Comment by irtemed88** [comment]
@ArtemMysik - This is the same issue I was facing. Have you tried following the instructions I outlined in my previous post?

**Comment by tapashmajumder** [comment]
@irtemed88 I am trying to first reproduce the problem and I am not able to repro this. Please note that I have attached IterableSDK.zip just two days ago. The previous one was not right.

@ArtemMysik Here is my sample code and it is working as expected.
```
import UIKit
import IterableSDK

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?


    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.

        let config = IterableConfig()
        config.urlDelegate = self
        IterableAPI.initialize(apiKey: "")
        
        return true
    }

    func applicationWillResignActive(_ application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
    }

    func applicationDidEnterBackground(_ application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }

    func applicationWillEnterForeground(_ application: UIApplication) {
        // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }

    func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
    }
}

extension AppDelegate : IterableURLDelegate {
    func handle(iterableURL url: URL, inContext context: IterableActionContext) -> Bool {
        return true
    }
}

```

**Comment by tapashmajumder** [comment]
@irtemed88 Can you please try with our latest zip file from 2019-04-23 (updated SDK version 6.0.8) and see if you are also seeing any problems?
[IterableSDK.zip](https://github.com/Iterable/swift-sdk/files/3119112/IterableSDK.zip)

**Comment by tapashmajumder** [comment]
@irtemed88 @ArtemMysik @tolgaarikan I was able to repro this using objc project. This works fine when using Swift but is a problem when using Objc. I am looking into this. In the meantime can you please confirm that you are using Objc? Thanks!

**Comment by irtemed88** [comment]
@tapashmajumder Yes my project was using objc.

**Comment by ArtemMysik** [comment]
@tapashmajumder Our project is using swift but we have bridging obj-c header for some libs

**Comment by tapashmajumder** [comment]
Thank you @irtemed88 @ArtemMysik. It appears I missed the objc part earlier and wasn't able to repro. Now I have reproduced and fixed the issue on our end. Many many thanks to @irtemed88.

I have attached the correct zip file which will work with objc code in both device/simulator.
I have also fixed our zip generation scripts. I am marking this issue as closed.
