### ISSUE TITLE
Cocoapods installation not working

### ISSUE THREAD

**Issue by PSBT** [Iterable/swift-sdk#83]
As mentioned in the automatic installation instructions I add the following to my pod file:
`pod 'Iterable-iOS-SDK'`

Then I do:
`pod install`

After that I open the workspace for my project, compile it, and I get the following compilation error:

`Pods/Iterable-iOS-SDK/swift-sdk/IterableSDK.h:19:9: 'IterableSDK/IterableConstants.h' file not found`

Is this a known issue? I'm on Xcode Version 10.1 (10B61).

Thanks!

**Comment by PSBT** [comment]
From the following link you'll be able to download an empty Xcode project that shows this problem:
https://www.dropbox.com/s/4wilvpi8owrf0li/IterableTest.zip?dl=0

**Comment by tapash-majumder** [comment]
There is something wrong with your Podfile. I am attaching the Podfile that worked for me. Please also remember to clean everything.
rm -rf Pods
rm -rf Pods.lock
rm -rf IterableTest.xcworkspace/
pod update
pod install

**Comment by tapash-majumder** [comment]
```
# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

use_frameworks!

target 'IterableTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for IterableTest
  pod 'Iterable-iOS-SDK'

  target 'IterableTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IterableTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by PSBT** [comment]
Sorry in the attached project I had forgotten to add `use_frameworks!` to the pod file. After adding that the empty Swift project compiles.

Though I still have the problem in my main project which is Obj-C. In that case how should the pod file look? `use_frameworks!` must be added to the pod file in that case too?

**Comment by tapash-majumder** [comment]
I have noticed that in the original Profile user_frameworks! was commented out. Are you sure about that? I changed the Podfile as below and it is still working.

```
# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'IterableTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for IterableTest
  pod 'Iterable-iOS-SDK'
  
  use_frameworks!


  target 'IterableTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IterableTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by PSBT** [comment]
Yes it was commented that was my mistake. I created that empty project for illustrative purposes only. After uncommented that line the sample project I created compiles. 

What I'm saying is that in our real project we can't use `use_frameworks!`. Looks like your pod requires that for the SDK to compile? Can you confirm that?

Is there a way to make it compile via pods without using `use_frameworks!`? Our real project is entirely Objective-C.

**Comment by PSBT** [comment]
I'm confused by the fact that your sample Podfile (https://raw.githubusercontent.com/Iterable/swift-sdk/master/sample-apps/swift-sample-app/Podfile) says this:

```
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
```

We are not using Swift in our project so that must remain commented, right? If we leave it commented then the project doesn't compile (error shown in my first message). If I uncomment it the code that uses other pods from other libraries start giving compilation errors…

**Comment by tapashmajumder** [comment]
Yes, you do need use_frameworks! I am not sure about other pods in other libraries. But I believe there should be a way to include use_frameworks! per target. 

Can you create a sample project that reproduces this problem?

If enabling use_frameworks! per target does not work then maybe the best option is to do manual installation of IterableSDK.framework.

**Comment by PSBT** [comment]
Got it! 

It's possible to use `use_frameworks!` per target but apparently not per pod (https://github.com/CocoaPods/CocoaPods/issues/3839).

Yeah so looks our only option is the manual installation.

Thanks!

**Comment by tapashmajumder** [comment]
Thanks @PSBT. Let us know if you have any issues with manual installation.
