### ISSUE TITLE
Type 'IterableHtmlInAppContent' does not conform to protocol 'Decodable'

### ISSUE THREAD

**Issue by BFMarks** [Iterable/swift-sdk#90]
```
@objcMembers
public class IterableHtmlInAppContent : NSObject, IterableInAppContent, Codable {
```
is throwing the error:

`Type 'IterableHtmlInAppContent' does not conform to protocol 'Decodable'`

Looks like the init function needs to be change.  I am on Swift 4 with XCode Version 10.1.  This is for  Iterable-iOS-SDK 6.1.0-beta3.

**Comment by tapashmajumder** [comment]
Please upgrade to Xcode 10.2.

**Comment by tapashmajumder** [comment]
Closing. Please reopen if the issue is not fixed.
